[package]
name = "mc-auto-updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
directories = "4.0"
reqwest = { version = "0.11.12", features = ["blocking"] }
zip = "0.6.3"